# Generated by Django 4.0.6 on 2022-09-10 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoping',
            old_name='user_name',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='shoping',
            name='password',
            field=models.CharField(max_length=10),
        ),
    ]
