# Generated by Django 4.0.6 on 2022-09-13 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_user_name_shoping_name_alter_shoping_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoping',
            name='image',
            field=models.ImageField(default=0, upload_to=''),
        ),
    ]
