# Generated by Django 4.0.6 on 2022-09-14 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoping',
            name='image',
        ),
    ]
