# Generated by Django 4.0.6 on 2022-09-14 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_rename_products_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='pro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_title', models.CharField(max_length=30)),
                ('pro_price', models.IntegerField(default=0)),
                ('pro_desc', models.CharField(max_length=50)),
                ('pro_image', models.ImageField(upload_to='images')),
            ],
        ),
    ]
