# Generated by Django 4.0.6 on 2022-09-14 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_pro'),
    ]

    operations = [
        migrations.DeleteModel(
            name='pro',
        ),
    ]
