# Generated by Django 4.0.6 on 2022-09-18 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_kidsproduct_womenproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kidsproduct',
            name='image',
            field=models.ImageField(upload_to='image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='image'),
        ),
        migrations.AlterField(
            model_name='womenproduct',
            name='image',
            field=models.ImageField(upload_to='image'),
        ),
    ]
