# Generated by Django 4.0.6 on 2022-09-18 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_kidsproduct_image_alter_product_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kidsproduct',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='shoping',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='womenproduct',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
