# Generated by Django 4.0.6 on 2022-09-20 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_alter_kidsproduct_id_alter_product_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='product',
            new_name='menproduct',
        ),
    ]
