# Generated by Django 4.0.6 on 2022-09-22 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='items_json',
        ),
    ]
