# Generated by Django 4.0.6 on 2022-09-23 18:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0020_cart'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cart',
            new_name='kcart',
        ),
        migrations.CreateModel(
            name='wcart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('kproduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.kidsproduct')),
                ('mproduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.menproduct')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('wproduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.womenproduct')),
            ],
        ),
        migrations.CreateModel(
            name='mcart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('kproduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.kidsproduct')),
                ('mproduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.menproduct')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('wproduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.womenproduct')),
            ],
        ),
    ]
