# Generated by Django 4.0.6 on 2022-09-24 09:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0022_rename_mcart_cart_remove_wcart_kproduct_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='kproduct',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='mproduct',
        ),
        migrations.CreateModel(
            name='kcart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('kproduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.kidsproduct')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
