# Generated by Django 4.0.6 on 2022-09-26 05:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0023_remove_cart_kproduct_remove_cart_mproduct_kcart'),
    ]

    operations = [
        migrations.CreateModel(
            name='mcart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('mproduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.kidsproduct')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
