# Generated by Django 4.0.6 on 2022-09-27 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_mcart'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoping',
            name='address',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mcart',
            name='mproduct',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.menproduct'),
        ),
    ]
