# Generated by Django 4.0.6 on 2022-09-27 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_shoping_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoping',
            name='user',
        ),
    ]
