# Generated by Django 4.0.6 on 2022-09-27 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_remove_shoping_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='shoping',
        ),
    ]
