# Generated by Django 4.0.6 on 2022-09-28 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0031_remove_order_id_order_order_id_alter_cart_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoping',
            name='user',
        ),
        migrations.AlterField(
            model_name='kidsproduct',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='menproduct',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='shoping',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='womenproduct',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
