# Generated by Django 4.0.6 on 2022-10-01 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0034_remove_order_order_id_order_id_alter_kidsproduct_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='shoping',
        ),
    ]
