# Generated by Django 4.0.6 on 2022-10-01 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0035_delete_shoping'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kcart',
            name='kproduct',
        ),
        migrations.RemoveField(
            model_name='kcart',
            name='user',
        ),
        migrations.RemoveField(
            model_name='mcart',
            name='mproduct',
        ),
        migrations.RemoveField(
            model_name='mcart',
            name='user',
        ),
        migrations.DeleteModel(
            name='cart',
        ),
        migrations.DeleteModel(
            name='kcart',
        ),
        migrations.DeleteModel(
            name='mcart',
        ),
    ]
