# Generated by Django 4.0.6 on 2022-10-01 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0036_remove_kcart_kproduct_remove_kcart_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='kidsproduct',
        ),
        migrations.DeleteModel(
            name='menproduct',
        ),
        migrations.DeleteModel(
            name='order',
        ),
        migrations.DeleteModel(
            name='womenproduct',
        ),
    ]
